//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Centralize.WebSite.Proxy.LocationProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RMS.Centralize.WebSite.Proxy.LocationProxy.LocationResult))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationResult", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService")]
    [System.SerializableAttribute()]
    public partial class LocationResult : RMS.Centralize.WebSite.Proxy.LocationProxy.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RMS.Centralize.WebSite.Proxy.LocationProxy.LocationInfo> ListLocationInfosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RMS.Centralize.WebSite.Proxy.LocationProxy.RmsLocation> ListLocationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RMS.Centralize.WebSite.Proxy.LocationProxy.RmsLocation LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RMS.Centralize.WebSite.Proxy.LocationProxy.LocationInfo> ListLocationInfos {
            get {
                return this.ListLocationInfosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListLocationInfosField, value) != true)) {
                    this.ListLocationInfosField = value;
                    this.RaisePropertyChanged("ListLocationInfos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RMS.Centralize.WebSite.Proxy.LocationProxy.RmsLocation> ListLocations {
            get {
                return this.ListLocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ListLocationsField, value) != true)) {
                    this.ListLocationsField = value;
                    this.RaisePropertyChanged("ListLocations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RMS.Centralize.WebSite.Proxy.LocationProxy.RmsLocation Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RmsLocation", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.DAL")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RMS.Centralize.WebSite.Proxy.LocationProxy.LocationInfo))]
    public partial class RmsLocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> MondayEnableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> MondayWholeDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> MondayStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> MondayEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> TuesdayEnableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> TuesdayWholeDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TuesdayStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TuesdayEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> WednesdayEnableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> WednesdayWholeDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> WednesdayStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> WednesdayEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ThursdayEnableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ThursdayWholeDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ThursdayStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ThursdayEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> FridayEnableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> FridayWholeDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FridayStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FridayEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SaturdayEnableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SaturdayWholeDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SaturdayStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SaturdayEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SundayEnableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SundayWholeDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SundayStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SundayEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string LocationCode {
            get {
                return this.LocationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationCodeField, value) != true)) {
                    this.LocationCodeField = value;
                    this.RaisePropertyChanged("LocationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<bool> MondayEnable {
            get {
                return this.MondayEnableField;
            }
            set {
                if ((this.MondayEnableField.Equals(value) != true)) {
                    this.MondayEnableField = value;
                    this.RaisePropertyChanged("MondayEnable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<bool> MondayWholeDay {
            get {
                return this.MondayWholeDayField;
            }
            set {
                if ((this.MondayWholeDayField.Equals(value) != true)) {
                    this.MondayWholeDayField = value;
                    this.RaisePropertyChanged("MondayWholeDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> MondayStart {
            get {
                return this.MondayStartField;
            }
            set {
                if ((this.MondayStartField.Equals(value) != true)) {
                    this.MondayStartField = value;
                    this.RaisePropertyChanged("MondayStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<System.DateTime> MondayEnd {
            get {
                return this.MondayEndField;
            }
            set {
                if ((this.MondayEndField.Equals(value) != true)) {
                    this.MondayEndField = value;
                    this.RaisePropertyChanged("MondayEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<bool> TuesdayEnable {
            get {
                return this.TuesdayEnableField;
            }
            set {
                if ((this.TuesdayEnableField.Equals(value) != true)) {
                    this.TuesdayEnableField = value;
                    this.RaisePropertyChanged("TuesdayEnable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<bool> TuesdayWholeDay {
            get {
                return this.TuesdayWholeDayField;
            }
            set {
                if ((this.TuesdayWholeDayField.Equals(value) != true)) {
                    this.TuesdayWholeDayField = value;
                    this.RaisePropertyChanged("TuesdayWholeDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<System.DateTime> TuesdayStart {
            get {
                return this.TuesdayStartField;
            }
            set {
                if ((this.TuesdayStartField.Equals(value) != true)) {
                    this.TuesdayStartField = value;
                    this.RaisePropertyChanged("TuesdayStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<System.DateTime> TuesdayEnd {
            get {
                return this.TuesdayEndField;
            }
            set {
                if ((this.TuesdayEndField.Equals(value) != true)) {
                    this.TuesdayEndField = value;
                    this.RaisePropertyChanged("TuesdayEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<bool> WednesdayEnable {
            get {
                return this.WednesdayEnableField;
            }
            set {
                if ((this.WednesdayEnableField.Equals(value) != true)) {
                    this.WednesdayEnableField = value;
                    this.RaisePropertyChanged("WednesdayEnable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Nullable<bool> WednesdayWholeDay {
            get {
                return this.WednesdayWholeDayField;
            }
            set {
                if ((this.WednesdayWholeDayField.Equals(value) != true)) {
                    this.WednesdayWholeDayField = value;
                    this.RaisePropertyChanged("WednesdayWholeDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.Nullable<System.DateTime> WednesdayStart {
            get {
                return this.WednesdayStartField;
            }
            set {
                if ((this.WednesdayStartField.Equals(value) != true)) {
                    this.WednesdayStartField = value;
                    this.RaisePropertyChanged("WednesdayStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public System.Nullable<System.DateTime> WednesdayEnd {
            get {
                return this.WednesdayEndField;
            }
            set {
                if ((this.WednesdayEndField.Equals(value) != true)) {
                    this.WednesdayEndField = value;
                    this.RaisePropertyChanged("WednesdayEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public System.Nullable<bool> ThursdayEnable {
            get {
                return this.ThursdayEnableField;
            }
            set {
                if ((this.ThursdayEnableField.Equals(value) != true)) {
                    this.ThursdayEnableField = value;
                    this.RaisePropertyChanged("ThursdayEnable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public System.Nullable<bool> ThursdayWholeDay {
            get {
                return this.ThursdayWholeDayField;
            }
            set {
                if ((this.ThursdayWholeDayField.Equals(value) != true)) {
                    this.ThursdayWholeDayField = value;
                    this.RaisePropertyChanged("ThursdayWholeDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public System.Nullable<System.DateTime> ThursdayStart {
            get {
                return this.ThursdayStartField;
            }
            set {
                if ((this.ThursdayStartField.Equals(value) != true)) {
                    this.ThursdayStartField = value;
                    this.RaisePropertyChanged("ThursdayStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public System.Nullable<System.DateTime> ThursdayEnd {
            get {
                return this.ThursdayEndField;
            }
            set {
                if ((this.ThursdayEndField.Equals(value) != true)) {
                    this.ThursdayEndField = value;
                    this.RaisePropertyChanged("ThursdayEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public System.Nullable<bool> FridayEnable {
            get {
                return this.FridayEnableField;
            }
            set {
                if ((this.FridayEnableField.Equals(value) != true)) {
                    this.FridayEnableField = value;
                    this.RaisePropertyChanged("FridayEnable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public System.Nullable<bool> FridayWholeDay {
            get {
                return this.FridayWholeDayField;
            }
            set {
                if ((this.FridayWholeDayField.Equals(value) != true)) {
                    this.FridayWholeDayField = value;
                    this.RaisePropertyChanged("FridayWholeDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public System.Nullable<System.DateTime> FridayStart {
            get {
                return this.FridayStartField;
            }
            set {
                if ((this.FridayStartField.Equals(value) != true)) {
                    this.FridayStartField = value;
                    this.RaisePropertyChanged("FridayStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public System.Nullable<System.DateTime> FridayEnd {
            get {
                return this.FridayEndField;
            }
            set {
                if ((this.FridayEndField.Equals(value) != true)) {
                    this.FridayEndField = value;
                    this.RaisePropertyChanged("FridayEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public System.Nullable<bool> SaturdayEnable {
            get {
                return this.SaturdayEnableField;
            }
            set {
                if ((this.SaturdayEnableField.Equals(value) != true)) {
                    this.SaturdayEnableField = value;
                    this.RaisePropertyChanged("SaturdayEnable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public System.Nullable<bool> SaturdayWholeDay {
            get {
                return this.SaturdayWholeDayField;
            }
            set {
                if ((this.SaturdayWholeDayField.Equals(value) != true)) {
                    this.SaturdayWholeDayField = value;
                    this.RaisePropertyChanged("SaturdayWholeDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public System.Nullable<System.DateTime> SaturdayStart {
            get {
                return this.SaturdayStartField;
            }
            set {
                if ((this.SaturdayStartField.Equals(value) != true)) {
                    this.SaturdayStartField = value;
                    this.RaisePropertyChanged("SaturdayStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public System.Nullable<System.DateTime> SaturdayEnd {
            get {
                return this.SaturdayEndField;
            }
            set {
                if ((this.SaturdayEndField.Equals(value) != true)) {
                    this.SaturdayEndField = value;
                    this.RaisePropertyChanged("SaturdayEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public System.Nullable<bool> SundayEnable {
            get {
                return this.SundayEnableField;
            }
            set {
                if ((this.SundayEnableField.Equals(value) != true)) {
                    this.SundayEnableField = value;
                    this.RaisePropertyChanged("SundayEnable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public System.Nullable<bool> SundayWholeDay {
            get {
                return this.SundayWholeDayField;
            }
            set {
                if ((this.SundayWholeDayField.Equals(value) != true)) {
                    this.SundayWholeDayField = value;
                    this.RaisePropertyChanged("SundayWholeDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public System.Nullable<System.DateTime> SundayStart {
            get {
                return this.SundayStartField;
            }
            set {
                if ((this.SundayStartField.Equals(value) != true)) {
                    this.SundayStartField = value;
                    this.RaisePropertyChanged("SundayStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public System.Nullable<System.DateTime> SundayEnd {
            get {
                return this.SundayEndField;
            }
            set {
                if ((this.SundayEndField.Equals(value) != true)) {
                    this.SundayEndField = value;
                    this.RaisePropertyChanged("SundayEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public System.Nullable<bool> ActiveList {
            get {
                return this.ActiveListField;
            }
            set {
                if ((this.ActiveListField.Equals(value) != true)) {
                    this.ActiveListField = value;
                    this.RaisePropertyChanged("ActiveList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=32)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=33)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=34)]
        public System.Nullable<System.DateTime> UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=35)]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationInfo", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService.Model")]
    [System.SerializableAttribute()]
    public partial class LocationInfo : RMS.Centralize.WebSite.Proxy.LocationProxy.RmsLocation {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RowNumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RowNum {
            get {
                return this.RowNumField;
            }
            set {
                if ((this.RowNumField.Equals(value) != true)) {
                    this.RowNumField = value;
                    this.RaisePropertyChanged("RowNum");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JQueryDataTableParamModel", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService.Model")]
    [System.SerializableAttribute()]
    public partial class JQueryDataTableParamModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iDisplayLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iDisplayStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iSortColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iSortingColsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sEchoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sSearchField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iColumns {
            get {
                return this.iColumnsField;
            }
            set {
                if ((this.iColumnsField.Equals(value) != true)) {
                    this.iColumnsField = value;
                    this.RaisePropertyChanged("iColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iDisplayLength {
            get {
                return this.iDisplayLengthField;
            }
            set {
                if ((this.iDisplayLengthField.Equals(value) != true)) {
                    this.iDisplayLengthField = value;
                    this.RaisePropertyChanged("iDisplayLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iDisplayStart {
            get {
                return this.iDisplayStartField;
            }
            set {
                if ((this.iDisplayStartField.Equals(value) != true)) {
                    this.iDisplayStartField = value;
                    this.RaisePropertyChanged("iDisplayStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iSortColumn {
            get {
                return this.iSortColumnField;
            }
            set {
                if ((object.ReferenceEquals(this.iSortColumnField, value) != true)) {
                    this.iSortColumnField = value;
                    this.RaisePropertyChanged("iSortColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iSortingCols {
            get {
                return this.iSortingColsField;
            }
            set {
                if ((this.iSortingColsField.Equals(value) != true)) {
                    this.iSortingColsField = value;
                    this.RaisePropertyChanged("iSortingCols");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sColumns {
            get {
                return this.sColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.sColumnsField, value) != true)) {
                    this.sColumnsField = value;
                    this.RaisePropertyChanged("sColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sEcho {
            get {
                return this.sEchoField;
            }
            set {
                if ((object.ReferenceEquals(this.sEchoField, value) != true)) {
                    this.sEchoField = value;
                    this.RaisePropertyChanged("sEcho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSearch {
            get {
                return this.sSearchField;
            }
            set {
                if ((object.ReferenceEquals(this.sSearchField, value) != true)) {
                    this.sSearchField = value;
                    this.RaisePropertyChanged("sSearch");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocationProxy.ILocationService")]
    public interface ILocationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/TestConnection", ReplyAction="http://tempuri.org/ILocationService/TestConnectionResponse")]
        void TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/TestConnection", ReplyAction="http://tempuri.org/ILocationService/TestConnectionResponse")]
        System.Threading.Tasks.Task TestConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/List", ReplyAction="http://tempuri.org/ILocationService/ListResponse")]
        RMS.Centralize.WebSite.Proxy.LocationProxy.LocationResult List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/List", ReplyAction="http://tempuri.org/ILocationService/ListResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.LocationProxy.LocationResult> ListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/Get", ReplyAction="http://tempuri.org/ILocationService/GetResponse")]
        RMS.Centralize.WebSite.Proxy.LocationProxy.LocationResult Get(int locationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/Get", ReplyAction="http://tempuri.org/ILocationService/GetResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.LocationProxy.LocationResult> GetAsync(int locationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/Search", ReplyAction="http://tempuri.org/ILocationService/SearchResponse")]
        RMS.Centralize.WebSite.Proxy.LocationProxy.LocationResult Search(RMS.Centralize.WebSite.Proxy.LocationProxy.JQueryDataTableParamModel param, string location, System.Nullable<bool> activeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/Search", ReplyAction="http://tempuri.org/ILocationService/SearchResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.LocationProxy.LocationResult> SearchAsync(RMS.Centralize.WebSite.Proxy.LocationProxy.JQueryDataTableParamModel param, string location, System.Nullable<bool> activeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/Update", ReplyAction="http://tempuri.org/ILocationService/UpdateResponse")]
        RMS.Centralize.WebSite.Proxy.LocationProxy.Result Update(
                    System.Nullable<int> id, 
                    string m, 
                    string locationCode, 
                    string locationName, 
                    bool mondayEnable, 
                    bool mondayWholeDay, 
                    System.Nullable<System.DateTime> mondayStart, 
                    System.Nullable<System.DateTime> mondayEnd, 
                    bool tuesdayEnable, 
                    bool tuesdayWholeDay, 
                    System.Nullable<System.DateTime> tuesdayStart, 
                    System.Nullable<System.DateTime> tuesdayEnd, 
                    bool wednesdayEnable, 
                    bool wednesdayWholeDay, 
                    System.Nullable<System.DateTime> wednesdayStart, 
                    System.Nullable<System.DateTime> wednesdayEnd, 
                    bool thursdayEnable, 
                    bool thursdayWholeDay, 
                    System.Nullable<System.DateTime> thursdayStart, 
                    System.Nullable<System.DateTime> thursdayEnd, 
                    bool fridayEnable, 
                    bool fridayWholeDay, 
                    System.Nullable<System.DateTime> fridayStart, 
                    System.Nullable<System.DateTime> fridayEnd, 
                    bool saturdayEnable, 
                    bool saturdayWholeDay, 
                    System.Nullable<System.DateTime> saturdayStart, 
                    System.Nullable<System.DateTime> saturdayEnd, 
                    bool sundayEnable, 
                    bool sundayWholeDay, 
                    System.Nullable<System.DateTime> sundayStart, 
                    System.Nullable<System.DateTime> sundayEnd, 
                    bool activeList, 
                    string updatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/Update", ReplyAction="http://tempuri.org/ILocationService/UpdateResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.LocationProxy.Result> UpdateAsync(
                    System.Nullable<int> id, 
                    string m, 
                    string locationCode, 
                    string locationName, 
                    bool mondayEnable, 
                    bool mondayWholeDay, 
                    System.Nullable<System.DateTime> mondayStart, 
                    System.Nullable<System.DateTime> mondayEnd, 
                    bool tuesdayEnable, 
                    bool tuesdayWholeDay, 
                    System.Nullable<System.DateTime> tuesdayStart, 
                    System.Nullable<System.DateTime> tuesdayEnd, 
                    bool wednesdayEnable, 
                    bool wednesdayWholeDay, 
                    System.Nullable<System.DateTime> wednesdayStart, 
                    System.Nullable<System.DateTime> wednesdayEnd, 
                    bool thursdayEnable, 
                    bool thursdayWholeDay, 
                    System.Nullable<System.DateTime> thursdayStart, 
                    System.Nullable<System.DateTime> thursdayEnd, 
                    bool fridayEnable, 
                    bool fridayWholeDay, 
                    System.Nullable<System.DateTime> fridayStart, 
                    System.Nullable<System.DateTime> fridayEnd, 
                    bool saturdayEnable, 
                    bool saturdayWholeDay, 
                    System.Nullable<System.DateTime> saturdayStart, 
                    System.Nullable<System.DateTime> saturdayEnd, 
                    bool sundayEnable, 
                    bool sundayWholeDay, 
                    System.Nullable<System.DateTime> sundayStart, 
                    System.Nullable<System.DateTime> sundayEnd, 
                    bool activeList, 
                    string updatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/Delete", ReplyAction="http://tempuri.org/ILocationService/DeleteResponse")]
        RMS.Centralize.WebSite.Proxy.LocationProxy.Result Delete(int locationID, string updatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/Delete", ReplyAction="http://tempuri.org/ILocationService/DeleteResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.LocationProxy.Result> DeleteAsync(int locationID, string updatedBy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocationServiceChannel : RMS.Centralize.WebSite.Proxy.LocationProxy.ILocationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocationServiceClient : System.ServiceModel.ClientBase<RMS.Centralize.WebSite.Proxy.LocationProxy.ILocationService>, RMS.Centralize.WebSite.Proxy.LocationProxy.ILocationService {
        
        public LocationServiceClient() {
        }
        
        public LocationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void TestConnection() {
            base.Channel.TestConnection();
        }
        
        public System.Threading.Tasks.Task TestConnectionAsync() {
            return base.Channel.TestConnectionAsync();
        }
        
        public RMS.Centralize.WebSite.Proxy.LocationProxy.LocationResult List() {
            return base.Channel.List();
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.LocationProxy.LocationResult> ListAsync() {
            return base.Channel.ListAsync();
        }
        
        public RMS.Centralize.WebSite.Proxy.LocationProxy.LocationResult Get(int locationID) {
            return base.Channel.Get(locationID);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.LocationProxy.LocationResult> GetAsync(int locationID) {
            return base.Channel.GetAsync(locationID);
        }
        
        public RMS.Centralize.WebSite.Proxy.LocationProxy.LocationResult Search(RMS.Centralize.WebSite.Proxy.LocationProxy.JQueryDataTableParamModel param, string location, System.Nullable<bool> activeList) {
            return base.Channel.Search(param, location, activeList);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.LocationProxy.LocationResult> SearchAsync(RMS.Centralize.WebSite.Proxy.LocationProxy.JQueryDataTableParamModel param, string location, System.Nullable<bool> activeList) {
            return base.Channel.SearchAsync(param, location, activeList);
        }
        
        public RMS.Centralize.WebSite.Proxy.LocationProxy.Result Update(
                    System.Nullable<int> id, 
                    string m, 
                    string locationCode, 
                    string locationName, 
                    bool mondayEnable, 
                    bool mondayWholeDay, 
                    System.Nullable<System.DateTime> mondayStart, 
                    System.Nullable<System.DateTime> mondayEnd, 
                    bool tuesdayEnable, 
                    bool tuesdayWholeDay, 
                    System.Nullable<System.DateTime> tuesdayStart, 
                    System.Nullable<System.DateTime> tuesdayEnd, 
                    bool wednesdayEnable, 
                    bool wednesdayWholeDay, 
                    System.Nullable<System.DateTime> wednesdayStart, 
                    System.Nullable<System.DateTime> wednesdayEnd, 
                    bool thursdayEnable, 
                    bool thursdayWholeDay, 
                    System.Nullable<System.DateTime> thursdayStart, 
                    System.Nullable<System.DateTime> thursdayEnd, 
                    bool fridayEnable, 
                    bool fridayWholeDay, 
                    System.Nullable<System.DateTime> fridayStart, 
                    System.Nullable<System.DateTime> fridayEnd, 
                    bool saturdayEnable, 
                    bool saturdayWholeDay, 
                    System.Nullable<System.DateTime> saturdayStart, 
                    System.Nullable<System.DateTime> saturdayEnd, 
                    bool sundayEnable, 
                    bool sundayWholeDay, 
                    System.Nullable<System.DateTime> sundayStart, 
                    System.Nullable<System.DateTime> sundayEnd, 
                    bool activeList, 
                    string updatedBy) {
            return base.Channel.Update(id, m, locationCode, locationName, mondayEnable, mondayWholeDay, mondayStart, mondayEnd, tuesdayEnable, tuesdayWholeDay, tuesdayStart, tuesdayEnd, wednesdayEnable, wednesdayWholeDay, wednesdayStart, wednesdayEnd, thursdayEnable, thursdayWholeDay, thursdayStart, thursdayEnd, fridayEnable, fridayWholeDay, fridayStart, fridayEnd, saturdayEnable, saturdayWholeDay, saturdayStart, saturdayEnd, sundayEnable, sundayWholeDay, sundayStart, sundayEnd, activeList, updatedBy);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.LocationProxy.Result> UpdateAsync(
                    System.Nullable<int> id, 
                    string m, 
                    string locationCode, 
                    string locationName, 
                    bool mondayEnable, 
                    bool mondayWholeDay, 
                    System.Nullable<System.DateTime> mondayStart, 
                    System.Nullable<System.DateTime> mondayEnd, 
                    bool tuesdayEnable, 
                    bool tuesdayWholeDay, 
                    System.Nullable<System.DateTime> tuesdayStart, 
                    System.Nullable<System.DateTime> tuesdayEnd, 
                    bool wednesdayEnable, 
                    bool wednesdayWholeDay, 
                    System.Nullable<System.DateTime> wednesdayStart, 
                    System.Nullable<System.DateTime> wednesdayEnd, 
                    bool thursdayEnable, 
                    bool thursdayWholeDay, 
                    System.Nullable<System.DateTime> thursdayStart, 
                    System.Nullable<System.DateTime> thursdayEnd, 
                    bool fridayEnable, 
                    bool fridayWholeDay, 
                    System.Nullable<System.DateTime> fridayStart, 
                    System.Nullable<System.DateTime> fridayEnd, 
                    bool saturdayEnable, 
                    bool saturdayWholeDay, 
                    System.Nullable<System.DateTime> saturdayStart, 
                    System.Nullable<System.DateTime> saturdayEnd, 
                    bool sundayEnable, 
                    bool sundayWholeDay, 
                    System.Nullable<System.DateTime> sundayStart, 
                    System.Nullable<System.DateTime> sundayEnd, 
                    bool activeList, 
                    string updatedBy) {
            return base.Channel.UpdateAsync(id, m, locationCode, locationName, mondayEnable, mondayWholeDay, mondayStart, mondayEnd, tuesdayEnable, tuesdayWholeDay, tuesdayStart, tuesdayEnd, wednesdayEnable, wednesdayWholeDay, wednesdayStart, wednesdayEnd, thursdayEnable, thursdayWholeDay, thursdayStart, thursdayEnd, fridayEnable, fridayWholeDay, fridayStart, fridayEnd, saturdayEnable, saturdayWholeDay, saturdayStart, saturdayEnd, sundayEnable, sundayWholeDay, sundayStart, sundayEnd, activeList, updatedBy);
        }
        
        public RMS.Centralize.WebSite.Proxy.LocationProxy.Result Delete(int locationID, string updatedBy) {
            return base.Channel.Delete(locationID, updatedBy);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.LocationProxy.Result> DeleteAsync(int locationID, string updatedBy) {
            return base.Channel.DeleteAsync(locationID, updatedBy);
        }
    }
}
