//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Centralize.WebSite.Proxy.MessageActionProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RMS.Centralize.WebSite.Proxy.MessageActionProxy.MessageActionResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RMS.Centralize.WebSite.Proxy.MessageActionProxy.InitialResult))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageActionResult", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService")]
    [System.SerializableAttribute()]
    public partial class MessageActionResult : RMS.Centralize.WebSite.Proxy.MessageActionProxy.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RMS.Centralize.WebSite.Proxy.MessageActionProxy.RmsMessageAction[] ListMessageActionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RMS.Centralize.WebSite.Proxy.MessageActionProxy.RmsMessageAction MessageActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RMS.Centralize.WebSite.Proxy.MessageActionProxy.RmsMessageAction[] ListMessageActions {
            get {
                return this.ListMessageActionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ListMessageActionsField, value) != true)) {
                    this.ListMessageActionsField = value;
                    this.RaisePropertyChanged("ListMessageActions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RMS.Centralize.WebSite.Proxy.MessageActionProxy.RmsMessageAction MessageAction {
            get {
                return this.MessageActionField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageActionField, value) != true)) {
                    this.MessageActionField = value;
                    this.RaisePropertyChanged("MessageAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InitialResult", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService")]
    [System.SerializableAttribute()]
    public partial class InitialResult : RMS.Centralize.WebSite.Proxy.MessageActionProxy.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeverityLevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageGroup {
            get {
                return this.MessageGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageGroupField, value) != true)) {
                    this.MessageGroupField = value;
                    this.RaisePropertyChanged("MessageGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeverityLevel {
            get {
                return this.SeverityLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.SeverityLevelField, value) != true)) {
                    this.SeverityLevelField = value;
                    this.RaisePropertyChanged("SeverityLevel");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RmsMessageAction", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService.Model")]
    [System.SerializableAttribute()]
    public partial class RmsMessageAction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionProfileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorTagEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorTagStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LevelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageGroupCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageGroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ReadOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RowNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionProfileName {
            get {
                return this.ActionProfileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionProfileNameField, value) != true)) {
                    this.ActionProfileNameField = value;
                    this.RaisePropertyChanged("ActionProfileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ActiveStatus {
            get {
                return this.ActiveStatusField;
            }
            set {
                if ((this.ActiveStatusField.Equals(value) != true)) {
                    this.ActiveStatusField = value;
                    this.RaisePropertyChanged("ActiveStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorTagEnd {
            get {
                return this.ColorTagEndField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorTagEndField, value) != true)) {
                    this.ColorTagEndField = value;
                    this.RaisePropertyChanged("ColorTagEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorTagStart {
            get {
                return this.ColorTagStartField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorTagStartField, value) != true)) {
                    this.ColorTagStartField = value;
                    this.RaisePropertyChanged("ColorTagStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LevelName {
            get {
                return this.LevelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelNameField, value) != true)) {
                    this.LevelNameField = value;
                    this.RaisePropertyChanged("LevelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageGroupCode {
            get {
                return this.MessageGroupCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageGroupCodeField, value) != true)) {
                    this.MessageGroupCodeField = value;
                    this.RaisePropertyChanged("MessageGroupCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageGroupName {
            get {
                return this.MessageGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageGroupNameField, value) != true)) {
                    this.MessageGroupNameField = value;
                    this.RaisePropertyChanged("MessageGroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((this.MessageIdField.Equals(value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ReadOnly {
            get {
                return this.ReadOnlyField;
            }
            set {
                if ((this.ReadOnlyField.Equals(value) != true)) {
                    this.ReadOnlyField = value;
                    this.RaisePropertyChanged("ReadOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RowNum {
            get {
                return this.RowNumField;
            }
            set {
                if ((this.RowNumField.Equals(value) != true)) {
                    this.RowNumField = value;
                    this.RaisePropertyChanged("RowNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JQueryDataTableParamModel", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService.Model")]
    [System.SerializableAttribute()]
    public partial class JQueryDataTableParamModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iDisplayLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iDisplayStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iSortColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iSortingColsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sEchoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sSearchField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iColumns {
            get {
                return this.iColumnsField;
            }
            set {
                if ((this.iColumnsField.Equals(value) != true)) {
                    this.iColumnsField = value;
                    this.RaisePropertyChanged("iColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iDisplayLength {
            get {
                return this.iDisplayLengthField;
            }
            set {
                if ((this.iDisplayLengthField.Equals(value) != true)) {
                    this.iDisplayLengthField = value;
                    this.RaisePropertyChanged("iDisplayLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iDisplayStart {
            get {
                return this.iDisplayStartField;
            }
            set {
                if ((this.iDisplayStartField.Equals(value) != true)) {
                    this.iDisplayStartField = value;
                    this.RaisePropertyChanged("iDisplayStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iSortColumn {
            get {
                return this.iSortColumnField;
            }
            set {
                if ((object.ReferenceEquals(this.iSortColumnField, value) != true)) {
                    this.iSortColumnField = value;
                    this.RaisePropertyChanged("iSortColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iSortingCols {
            get {
                return this.iSortingColsField;
            }
            set {
                if ((this.iSortingColsField.Equals(value) != true)) {
                    this.iSortingColsField = value;
                    this.RaisePropertyChanged("iSortingCols");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sColumns {
            get {
                return this.sColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.sColumnsField, value) != true)) {
                    this.sColumnsField = value;
                    this.RaisePropertyChanged("sColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sEcho {
            get {
                return this.sEchoField;
            }
            set {
                if ((object.ReferenceEquals(this.sEchoField, value) != true)) {
                    this.sEchoField = value;
                    this.RaisePropertyChanged("sEcho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSearch {
            get {
                return this.sSearchField;
            }
            set {
                if ((object.ReferenceEquals(this.sSearchField, value) != true)) {
                    this.sSearchField = value;
                    this.RaisePropertyChanged("sSearch");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageActionProxy.IMessageActionService")]
    public interface IMessageActionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageActionService/InitDataForMeesageAction", ReplyAction="http://tempuri.org/IMessageActionService/InitDataForMeesageActionResponse")]
        RMS.Centralize.WebSite.Proxy.MessageActionProxy.InitialResult InitDataForMeesageAction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageActionService/InitDataForMeesageAction", ReplyAction="http://tempuri.org/IMessageActionService/InitDataForMeesageActionResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.MessageActionProxy.InitialResult> InitDataForMeesageActionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageActionService/Search", ReplyAction="http://tempuri.org/IMessageActionService/SearchResponse")]
        RMS.Centralize.WebSite.Proxy.MessageActionProxy.MessageActionResult Search(RMS.Centralize.WebSite.Proxy.MessageActionProxy.JQueryDataTableParamModel param, System.Nullable<int> messageGroupID, string message, bool activeStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageActionService/Search", ReplyAction="http://tempuri.org/IMessageActionService/SearchResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.MessageActionProxy.MessageActionResult> SearchAsync(RMS.Centralize.WebSite.Proxy.MessageActionProxy.JQueryDataTableParamModel param, System.Nullable<int> messageGroupID, string message, bool activeStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageActionService/Delete", ReplyAction="http://tempuri.org/IMessageActionService/DeleteResponse")]
        RMS.Centralize.WebSite.Proxy.MessageActionProxy.Result Delete(System.Nullable<int> actionProfileID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageActionService/Delete", ReplyAction="http://tempuri.org/IMessageActionService/DeleteResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.MessageActionProxy.Result> DeleteAsync(System.Nullable<int> actionProfileID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageActionService/InitDataForMeesageEdit", ReplyAction="http://tempuri.org/IMessageActionService/InitDataForMeesageEditResponse")]
        RMS.Centralize.WebSite.Proxy.MessageActionProxy.InitialResult InitDataForMeesageEdit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageActionService/InitDataForMeesageEdit", ReplyAction="http://tempuri.org/IMessageActionService/InitDataForMeesageEditResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.MessageActionProxy.InitialResult> InitDataForMeesageEditAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageActionService/Get", ReplyAction="http://tempuri.org/IMessageActionService/GetResponse")]
        RMS.Centralize.WebSite.Proxy.MessageActionProxy.MessageActionResult Get(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageActionService/Get", ReplyAction="http://tempuri.org/IMessageActionService/GetResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.MessageActionProxy.MessageActionResult> GetAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageActionService/UpdateMessage", ReplyAction="http://tempuri.org/IMessageActionService/UpdateMessageResponse")]
        RMS.Centralize.WebSite.Proxy.MessageActionProxy.Result UpdateMessage(System.Nullable<int> id, string m, System.Nullable<int> messageGroupID, string message, System.Nullable<int> severityLevelID, bool activeList, bool activeStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageActionService/UpdateMessage", ReplyAction="http://tempuri.org/IMessageActionService/UpdateMessageResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.MessageActionProxy.Result> UpdateMessageAsync(System.Nullable<int> id, string m, System.Nullable<int> messageGroupID, string message, System.Nullable<int> severityLevelID, bool activeList, bool activeStatus);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageActionServiceChannel : RMS.Centralize.WebSite.Proxy.MessageActionProxy.IMessageActionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageActionServiceClient : System.ServiceModel.ClientBase<RMS.Centralize.WebSite.Proxy.MessageActionProxy.IMessageActionService>, RMS.Centralize.WebSite.Proxy.MessageActionProxy.IMessageActionService {
        
        public MessageActionServiceClient() {
        }
        
        public MessageActionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageActionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageActionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageActionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RMS.Centralize.WebSite.Proxy.MessageActionProxy.InitialResult InitDataForMeesageAction() {
            return base.Channel.InitDataForMeesageAction();
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.MessageActionProxy.InitialResult> InitDataForMeesageActionAsync() {
            return base.Channel.InitDataForMeesageActionAsync();
        }
        
        public RMS.Centralize.WebSite.Proxy.MessageActionProxy.MessageActionResult Search(RMS.Centralize.WebSite.Proxy.MessageActionProxy.JQueryDataTableParamModel param, System.Nullable<int> messageGroupID, string message, bool activeStatus) {
            return base.Channel.Search(param, messageGroupID, message, activeStatus);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.MessageActionProxy.MessageActionResult> SearchAsync(RMS.Centralize.WebSite.Proxy.MessageActionProxy.JQueryDataTableParamModel param, System.Nullable<int> messageGroupID, string message, bool activeStatus) {
            return base.Channel.SearchAsync(param, messageGroupID, message, activeStatus);
        }
        
        public RMS.Centralize.WebSite.Proxy.MessageActionProxy.Result Delete(System.Nullable<int> actionProfileID) {
            return base.Channel.Delete(actionProfileID);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.MessageActionProxy.Result> DeleteAsync(System.Nullable<int> actionProfileID) {
            return base.Channel.DeleteAsync(actionProfileID);
        }
        
        public RMS.Centralize.WebSite.Proxy.MessageActionProxy.InitialResult InitDataForMeesageEdit() {
            return base.Channel.InitDataForMeesageEdit();
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.MessageActionProxy.InitialResult> InitDataForMeesageEditAsync() {
            return base.Channel.InitDataForMeesageEditAsync();
        }
        
        public RMS.Centralize.WebSite.Proxy.MessageActionProxy.MessageActionResult Get(System.Nullable<int> id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.MessageActionProxy.MessageActionResult> GetAsync(System.Nullable<int> id) {
            return base.Channel.GetAsync(id);
        }
        
        public RMS.Centralize.WebSite.Proxy.MessageActionProxy.Result UpdateMessage(System.Nullable<int> id, string m, System.Nullable<int> messageGroupID, string message, System.Nullable<int> severityLevelID, bool activeList, bool activeStatus) {
            return base.Channel.UpdateMessage(id, m, messageGroupID, message, severityLevelID, activeList, activeStatus);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.MessageActionProxy.Result> UpdateMessageAsync(System.Nullable<int> id, string m, System.Nullable<int> messageGroupID, string message, System.Nullable<int> severityLevelID, bool activeList, bool activeStatus) {
            return base.Channel.UpdateMessageAsync(id, m, messageGroupID, message, severityLevelID, activeList, activeStatus);
        }
    }
}
