//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.ClientMonitoringResult))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientMonitoringResult", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService")]
    [System.SerializableAttribute()]
    public partial class ClientMonitoringResult : RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.ClientMonitoringInfo> ListMonitoringProfileInfosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.RmsClientMonitoring> ListMonitoringProfilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.RmsClientMonitoring MonitoringProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.ClientMonitoringInfo MonitoringProfileInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.ClientMonitoringInfo> ListMonitoringProfileInfos {
            get {
                return this.ListMonitoringProfileInfosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListMonitoringProfileInfosField, value) != true)) {
                    this.ListMonitoringProfileInfosField = value;
                    this.RaisePropertyChanged("ListMonitoringProfileInfos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.RmsClientMonitoring> ListMonitoringProfiles {
            get {
                return this.ListMonitoringProfilesField;
            }
            set {
                if ((object.ReferenceEquals(this.ListMonitoringProfilesField, value) != true)) {
                    this.ListMonitoringProfilesField = value;
                    this.RaisePropertyChanged("ListMonitoringProfiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.RmsClientMonitoring MonitoringProfile {
            get {
                return this.MonitoringProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.MonitoringProfileField, value) != true)) {
                    this.MonitoringProfileField = value;
                    this.RaisePropertyChanged("MonitoringProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.ClientMonitoringInfo MonitoringProfileInfo {
            get {
                return this.MonitoringProfileInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.MonitoringProfileInfoField, value) != true)) {
                    this.MonitoringProfileInfoField = value;
                    this.RaisePropertyChanged("MonitoringProfileInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RmsClientMonitoring", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.DAL")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.ClientMonitoringInfo))]
    public partial class RmsClientMonitoring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ClientIdField;
        
        private int MonitoringProfileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EffectiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MonitoringProfileId {
            get {
                return this.MonitoringProfileIdField;
            }
            set {
                if ((this.MonitoringProfileIdField.Equals(value) != true)) {
                    this.MonitoringProfileIdField = value;
                    this.RaisePropertyChanged("MonitoringProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> EffectiveDate {
            get {
                return this.EffectiveDateField;
            }
            set {
                if ((this.EffectiveDateField.Equals(value) != true)) {
                    this.EffectiveDateField = value;
                    this.RaisePropertyChanged("EffectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientMonitoringInfo", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService.Model")]
    [System.SerializableAttribute()]
    public partial class ClientMonitoringInfo : RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.RmsClientMonitoring {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RowNumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileName {
            get {
                return this.ProfileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileNameField, value) != true)) {
                    this.ProfileNameField = value;
                    this.RaisePropertyChanged("ProfileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RowNum {
            get {
                return this.RowNumField;
            }
            set {
                if ((this.RowNumField.Equals(value) != true)) {
                    this.RowNumField = value;
                    this.RaisePropertyChanged("RowNum");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientMonitoringProxy.IClientMonitoringService")]
    public interface IClientMonitoringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientMonitoringService/TestConnection", ReplyAction="http://tempuri.org/IClientMonitoringService/TestConnectionResponse")]
        void TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientMonitoringService/TestConnection", ReplyAction="http://tempuri.org/IClientMonitoringService/TestConnectionResponse")]
        System.Threading.Tasks.Task TestConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientMonitoringService/ListByClient", ReplyAction="http://tempuri.org/IClientMonitoringService/ListByClientResponse")]
        RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.ClientMonitoringResult ListByClient(int clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientMonitoringService/ListByClient", ReplyAction="http://tempuri.org/IClientMonitoringService/ListByClientResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.ClientMonitoringResult> ListByClientAsync(int clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientMonitoringService/Get", ReplyAction="http://tempuri.org/IClientMonitoringService/GetResponse")]
        RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.ClientMonitoringResult Get(int clientID, int monitoringProfileID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientMonitoringService/Get", ReplyAction="http://tempuri.org/IClientMonitoringService/GetResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.ClientMonitoringResult> GetAsync(int clientID, int monitoringProfileID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientMonitoringService/Update", ReplyAction="http://tempuri.org/IClientMonitoringService/UpdateResponse")]
        RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.Result Update(int clientID, int monitoringProfileID, string m, System.DateTime effectiveDate, string updatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientMonitoringService/Update", ReplyAction="http://tempuri.org/IClientMonitoringService/UpdateResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.Result> UpdateAsync(int clientID, int monitoringProfileID, string m, System.DateTime effectiveDate, string updatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientMonitoringService/Delete", ReplyAction="http://tempuri.org/IClientMonitoringService/DeleteResponse")]
        RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.Result Delete(int clientID, int monitoringProfileID, string updatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientMonitoringService/Delete", ReplyAction="http://tempuri.org/IClientMonitoringService/DeleteResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.Result> DeleteAsync(int clientID, int monitoringProfileID, string updatedBy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientMonitoringServiceChannel : RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.IClientMonitoringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientMonitoringServiceClient : System.ServiceModel.ClientBase<RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.IClientMonitoringService>, RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.IClientMonitoringService {
        
        public ClientMonitoringServiceClient() {
        }
        
        public ClientMonitoringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientMonitoringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientMonitoringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientMonitoringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void TestConnection() {
            base.Channel.TestConnection();
        }
        
        public System.Threading.Tasks.Task TestConnectionAsync() {
            return base.Channel.TestConnectionAsync();
        }
        
        public RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.ClientMonitoringResult ListByClient(int clientID) {
            return base.Channel.ListByClient(clientID);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.ClientMonitoringResult> ListByClientAsync(int clientID) {
            return base.Channel.ListByClientAsync(clientID);
        }
        
        public RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.ClientMonitoringResult Get(int clientID, int monitoringProfileID) {
            return base.Channel.Get(clientID, monitoringProfileID);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.ClientMonitoringResult> GetAsync(int clientID, int monitoringProfileID) {
            return base.Channel.GetAsync(clientID, monitoringProfileID);
        }
        
        public RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.Result Update(int clientID, int monitoringProfileID, string m, System.DateTime effectiveDate, string updatedBy) {
            return base.Channel.Update(clientID, monitoringProfileID, m, effectiveDate, updatedBy);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.Result> UpdateAsync(int clientID, int monitoringProfileID, string m, System.DateTime effectiveDate, string updatedBy) {
            return base.Channel.UpdateAsync(clientID, monitoringProfileID, m, effectiveDate, updatedBy);
        }
        
        public RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.Result Delete(int clientID, int monitoringProfileID, string updatedBy) {
            return base.Channel.Delete(clientID, monitoringProfileID, updatedBy);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ClientMonitoringProxy.Result> DeleteAsync(int clientID, int monitoringProfileID, string updatedBy) {
            return base.Channel.DeleteAsync(clientID, monitoringProfileID, updatedBy);
        }
    }
}
