//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Centralize.WebSite.Proxy.ActionProfileProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JQueryDataTableParamModel", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService.Model")]
    [System.SerializableAttribute()]
    public partial class JQueryDataTableParamModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iDisplayLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iDisplayStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iSortColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iSortingColsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sEchoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sSearchField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iColumns {
            get {
                return this.iColumnsField;
            }
            set {
                if ((this.iColumnsField.Equals(value) != true)) {
                    this.iColumnsField = value;
                    this.RaisePropertyChanged("iColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iDisplayLength {
            get {
                return this.iDisplayLengthField;
            }
            set {
                if ((this.iDisplayLengthField.Equals(value) != true)) {
                    this.iDisplayLengthField = value;
                    this.RaisePropertyChanged("iDisplayLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iDisplayStart {
            get {
                return this.iDisplayStartField;
            }
            set {
                if ((this.iDisplayStartField.Equals(value) != true)) {
                    this.iDisplayStartField = value;
                    this.RaisePropertyChanged("iDisplayStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iSortColumn {
            get {
                return this.iSortColumnField;
            }
            set {
                if ((object.ReferenceEquals(this.iSortColumnField, value) != true)) {
                    this.iSortColumnField = value;
                    this.RaisePropertyChanged("iSortColumn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iSortingCols {
            get {
                return this.iSortingColsField;
            }
            set {
                if ((this.iSortingColsField.Equals(value) != true)) {
                    this.iSortingColsField = value;
                    this.RaisePropertyChanged("iSortingCols");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sColumns {
            get {
                return this.sColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.sColumnsField, value) != true)) {
                    this.sColumnsField = value;
                    this.RaisePropertyChanged("sColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sEcho {
            get {
                return this.sEchoField;
            }
            set {
                if ((object.ReferenceEquals(this.sEchoField, value) != true)) {
                    this.sEchoField = value;
                    this.RaisePropertyChanged("sEcho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSearch {
            get {
                return this.sSearchField;
            }
            set {
                if ((object.ReferenceEquals(this.sSearchField, value) != true)) {
                    this.sSearchField = value;
                    this.RaisePropertyChanged("sSearch");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RMS.Centralize.WebSite.Proxy.ActionProfileProxy.ActionProfileResult))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionProfileResult", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.WebService")]
    [System.SerializableAttribute()]
    public partial class ActionProfileResult : RMS.Centralize.WebSite.Proxy.ActionProfileProxy.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RMS.Centralize.WebSite.Proxy.ActionProfileProxy.RmsActionProfile ActionProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RMS.Centralize.WebSite.Proxy.ActionProfileProxy.RmsActionProfile> ListActionProfilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RMS.Centralize.WebSite.Proxy.ActionProfileProxy.RmsActionProfile ActionProfile {
            get {
                return this.ActionProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionProfileField, value) != true)) {
                    this.ActionProfileField = value;
                    this.RaisePropertyChanged("ActionProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RMS.Centralize.WebSite.Proxy.ActionProfileProxy.RmsActionProfile> ListActionProfiles {
            get {
                return this.ListActionProfilesField;
            }
            set {
                if ((object.ReferenceEquals(this.ListActionProfilesField, value) != true)) {
                    this.ListActionProfilesField = value;
                    this.RaisePropertyChanged("ListActionProfiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RmsActionProfile", Namespace="http://schemas.datacontract.org/2004/07/RMS.Centralize.DAL")]
    [System.SerializableAttribute()]
    public partial class RmsActionProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ActionProfileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionProfileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CommandLineIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RowNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ActionProfileId {
            get {
                return this.ActionProfileIdField;
            }
            set {
                if ((this.ActionProfileIdField.Equals(value) != true)) {
                    this.ActionProfileIdField = value;
                    this.RaisePropertyChanged("ActionProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionProfileName {
            get {
                return this.ActionProfileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionProfileNameField, value) != true)) {
                    this.ActionProfileNameField = value;
                    this.RaisePropertyChanged("ActionProfileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sms {
            get {
                return this.SmsField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsField, value) != true)) {
                    this.SmsField = value;
                    this.RaisePropertyChanged("Sms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> CommandLineId {
            get {
                return this.CommandLineIdField;
            }
            set {
                if ((this.CommandLineIdField.Equals(value) != true)) {
                    this.CommandLineIdField = value;
                    this.RaisePropertyChanged("CommandLineId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<bool> ActiveList {
            get {
                return this.ActiveListField;
            }
            set {
                if ((this.ActiveListField.Equals(value) != true)) {
                    this.ActiveListField = value;
                    this.RaisePropertyChanged("ActiveList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<System.DateTime> UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<long> RowNum {
            get {
                return this.RowNumField;
            }
            set {
                if ((this.RowNumField.Equals(value) != true)) {
                    this.RowNumField = value;
                    this.RaisePropertyChanged("RowNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActionProfileProxy.IActionProfileService")]
    public interface IActionProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionProfileService/Search", ReplyAction="http://tempuri.org/IActionProfileService/SearchResponse")]
        RMS.Centralize.WebSite.Proxy.ActionProfileProxy.ActionProfileResult Search(RMS.Centralize.WebSite.Proxy.ActionProfileProxy.JQueryDataTableParamModel param, string txtActionProfile, string txtEmail, string txtSms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionProfileService/Search", ReplyAction="http://tempuri.org/IActionProfileService/SearchResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ActionProfileProxy.ActionProfileResult> SearchAsync(RMS.Centralize.WebSite.Proxy.ActionProfileProxy.JQueryDataTableParamModel param, string txtActionProfile, string txtEmail, string txtSms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionProfileService/Delete", ReplyAction="http://tempuri.org/IActionProfileService/DeleteResponse")]
        RMS.Centralize.WebSite.Proxy.ActionProfileProxy.Result Delete(System.Nullable<int> actionProfileID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionProfileService/Delete", ReplyAction="http://tempuri.org/IActionProfileService/DeleteResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ActionProfileProxy.Result> DeleteAsync(System.Nullable<int> actionProfileID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionProfileService/Get", ReplyAction="http://tempuri.org/IActionProfileService/GetResponse")]
        RMS.Centralize.WebSite.Proxy.ActionProfileProxy.ActionProfileResult Get(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionProfileService/Get", ReplyAction="http://tempuri.org/IActionProfileService/GetResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ActionProfileProxy.ActionProfileResult> GetAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionProfileService/Update", ReplyAction="http://tempuri.org/IActionProfileService/UpdateResponse")]
        RMS.Centralize.WebSite.Proxy.ActionProfileProxy.Result Update(System.Nullable<int> id, string m, string ActionProfileName, string Email, string SMS, bool ActiveList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionProfileService/Update", ReplyAction="http://tempuri.org/IActionProfileService/UpdateResponse")]
        System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ActionProfileProxy.Result> UpdateAsync(System.Nullable<int> id, string m, string ActionProfileName, string Email, string SMS, bool ActiveList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IActionProfileServiceChannel : RMS.Centralize.WebSite.Proxy.ActionProfileProxy.IActionProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActionProfileServiceClient : System.ServiceModel.ClientBase<RMS.Centralize.WebSite.Proxy.ActionProfileProxy.IActionProfileService>, RMS.Centralize.WebSite.Proxy.ActionProfileProxy.IActionProfileService {
        
        public ActionProfileServiceClient() {
        }
        
        public ActionProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActionProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActionProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActionProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RMS.Centralize.WebSite.Proxy.ActionProfileProxy.ActionProfileResult Search(RMS.Centralize.WebSite.Proxy.ActionProfileProxy.JQueryDataTableParamModel param, string txtActionProfile, string txtEmail, string txtSms) {
            return base.Channel.Search(param, txtActionProfile, txtEmail, txtSms);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ActionProfileProxy.ActionProfileResult> SearchAsync(RMS.Centralize.WebSite.Proxy.ActionProfileProxy.JQueryDataTableParamModel param, string txtActionProfile, string txtEmail, string txtSms) {
            return base.Channel.SearchAsync(param, txtActionProfile, txtEmail, txtSms);
        }
        
        public RMS.Centralize.WebSite.Proxy.ActionProfileProxy.Result Delete(System.Nullable<int> actionProfileID) {
            return base.Channel.Delete(actionProfileID);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ActionProfileProxy.Result> DeleteAsync(System.Nullable<int> actionProfileID) {
            return base.Channel.DeleteAsync(actionProfileID);
        }
        
        public RMS.Centralize.WebSite.Proxy.ActionProfileProxy.ActionProfileResult Get(System.Nullable<int> id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ActionProfileProxy.ActionProfileResult> GetAsync(System.Nullable<int> id) {
            return base.Channel.GetAsync(id);
        }
        
        public RMS.Centralize.WebSite.Proxy.ActionProfileProxy.Result Update(System.Nullable<int> id, string m, string ActionProfileName, string Email, string SMS, bool ActiveList) {
            return base.Channel.Update(id, m, ActionProfileName, Email, SMS, ActiveList);
        }
        
        public System.Threading.Tasks.Task<RMS.Centralize.WebSite.Proxy.ActionProfileProxy.Result> UpdateAsync(System.Nullable<int> id, string m, string ActionProfileName, string Email, string SMS, bool ActiveList) {
            return base.Channel.UpdateAsync(id, m, ActionProfileName, Email, SMS, ActiveList);
        }
    }
}
